spring.application.name=demo
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://localhost:5432/phishguard
spring.datasource.username=postgres
spring.datasource.password=P/k#\\-MQ

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring:
  ai:
    google:
      api-key: ${AIzaSyAVGjJe7up_cUzcd-1bE_B08PStj2C-ePI}