spring.application.name=demo

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/phishguard}
spring.datasource.username=${DB_USERNAME: postgres}
spring.datasource.password=${DB_PASSWORD: P/k#\\-MQ}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
groq.api.key=${GROQ_API_KEY: chave_local}
jwt.secret=${JWT_SECRET::chave-local-desenvolvimento-phishguard-2026-minimo-32-caracteres}